version: "{build}"
environment:
    msvc_version: 14
    python_version: 3.5
    rust_version: 1.12.1
    bintray_username: micbou
    bintray_api_key:
        secure: B1GlaWpEZ4f1oU6Hfi0XKe/LUoqJgJVUtXP8QxENtezlyNDqvRMfw1gX7btpEYk9
    twitter_consumer_key:
        secure: aohf6ZTz+kDR1CpuSXhDgCEqWe0/k7M1MfNtMlNwRLw=
    twitter_consumer_secret:
        secure: 4ZR4VoPu/8/a/tMPpMM41vwcAz+OeYfQ4dfiE99Pmqz0dSCiDpsO22cC11Sr53BcK+UZzQBH68ppB71nmjk6Mw==
    twitter_access_token:
        secure: KBY9gZq2RJzAIHCea6h+nTCIBiNQgTipI3lL0WPz1N6GXuOgikVQWWuaf+cFhXL0Lh2UgQuFHm2zDByFSXmkMQ==
    twitter_access_token_secret:
        secure: z66tC6HWZZ7dXS5SG49amgEGBfR6vX3SXQUjgV1GmFuaVFDXr67XZfK/dG3x8+pA
    USE_CLANG_COMPLETER: true
    matrix:
        - arch: 32
        - arch: 64
install:
    - ps: appveyor\install.ps1
build_script:
    - python appveyor\build.py --msvc %msvc_version%
    - ps: appveyor\variables.ps1
    - python appveyor\package.py %ycmd_artifact%
test: off
artifacts:
    - path: $(ycmd_artifact)
      name: ycmd
deploy:
    - tag: $(appveyor_repo_tag_name)
      release: $(ycmd_version)
      description: $(github_description)
      provider: GitHub
      auth_token:
          secure: gm7NWc/q5jrfYIipgRGs8Xd8+4BmWeEAEgfnCJYcu2EpgFdAxIMcT6ixBCE2gg5F
      artifact: ycmd
      draft: false
      prerelease: false
      on:
          branch: master
          appveyor_repo_tag: true
          msvc: 14
# Deploy to Bintray and send a tweet
# after_deploy:
#     - python appveyor\bintray.py upload generic ycmd %ycmd_version% %ycmd_artifact% --override
#     - python appveyor\bintray.py update-version generic ycmd %ycmd_version% "%bintray_description%" --vcs-tag %appveyor_repo_tag_name%
#     - python appveyor\bintray.py publish generic ycmd %ycmd_version%
#     - python appveyor\bintray.py download-list generic %ycmd_artifact% add
#     - python appveyor\twitt.py "%vim_tweet%"
